[package]
name = "p11scope-ebpf"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[features]
small-ring = ["p11scope-ebpf-common/small-ring"]

[dependencies]
aya-ebpf = "=0.2.1"
p11scope-ebpf-common = { path = "../ebpf-common" }

[[bin]]
name = "p11scope-ebpf"
path = "src/main.rs"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1

[workspace]
